

music:
  mysql:
    database: music
    host: localhost
  upload:
    location: /Users/qiao_yang/Desktop/stw/music/songs/upload/
  crawler: /Users/qiao_yang/Desktop/stw/music/songs/crawler/crawler.py
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: song
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  application:
    name: song
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:9200

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:xml/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 9090
server:
  port: 9020