spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: selfmusic
    url: jdbc:mysql://localhost:3306/selfmusic?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 977372ysj
  application:
    name: user
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 1000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/ysj/mapper/xml/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 9090

server:
  port: 9010