version: '3.2'

services:
  eureka:
    build: ./eureka
    ports:
      - "19010:8080"

  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      LANG: C.UTF-8

  redis:
    image: redis:6.2.1

  user:
    build: ./user

  song:
    build: ./song

  gateway:
    build: ./gateway
    ports:
      - "8090:8080"


