spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: myuser
          uri: lb://user
          predicates:
            - Path=/user/**

        - id: music
          uri: lb://song
          predicates:
            - Path=/song/**

  redis:
    database: 0
    host: redis
    port: 6379
    timeout: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 9090


server:
  port: 9000