spring:
  application:
    name: eureka
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: true
    fetch-reg istry: false