spring:
  application:
    name: eureka
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-reg istry: false
  instance:
    hostname: eureka